/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_contentobjects_jnotify_linux_JNotify_linux */

#ifndef _Included_net_contentobjects_jnotify_linux_JNotify_linux
#define _Included_net_contentobjects_jnotify_linux_JNotify_linux
#ifdef __cplusplus
extern "C" {
#endif
#undef net_contentobjects_jnotify_linux_JNotify_linux_IN_ACCESS
#define net_contentobjects_jnotify_linux_JNotify_linux_IN_ACCESS 1L
#undef net_contentobjects_jnotify_linux_JNotify_linux_IN_MODIFY
#define net_contentobjects_jnotify_linux_JNotify_linux_IN_MODIFY 2L
#undef net_contentobjects_jnotify_linux_JNotify_linux_IN_ATTRIB
#define net_contentobjects_jnotify_linux_JNotify_linux_IN_ATTRIB 4L
#undef net_contentobjects_jnotify_linux_JNotify_linux_IN_CLOSE_WRITE
#define net_contentobjects_jnotify_linux_JNotify_linux_IN_CLOSE_WRITE 8L
#undef net_contentobjects_jnotify_linux_JNotify_linux_IN_CLOSE_NOWRITE
#define net_contentobjects_jnotify_linux_JNotify_linux_IN_CLOSE_NOWRITE 16L
#undef net_contentobjects_jnotify_linux_JNotify_linux_IN_OPEN
#define net_contentobjects_jnotify_linux_JNotify_linux_IN_OPEN 32L
#undef net_contentobjects_jnotify_linux_JNotify_linux_IN_MOVED_FROM
#define net_contentobjects_jnotify_linux_JNotify_linux_IN_MOVED_FROM 64L
#undef net_contentobjects_jnotify_linux_JNotify_linux_IN_MOVED_TO
#define net_contentobjects_jnotify_linux_JNotify_linux_IN_MOVED_TO 128L
#undef net_contentobjects_jnotify_linux_JNotify_linux_IN_CREATE
#define net_contentobjects_jnotify_linux_JNotify_linux_IN_CREATE 256L
#undef net_contentobjects_jnotify_linux_JNotify_linux_IN_DELETE
#define net_contentobjects_jnotify_linux_JNotify_linux_IN_DELETE 512L
#undef net_contentobjects_jnotify_linux_JNotify_linux_IN_DELETE_SELF
#define net_contentobjects_jnotify_linux_JNotify_linux_IN_DELETE_SELF 1024L
#undef net_contentobjects_jnotify_linux_JNotify_linux_IN_MOVE_SELF
#define net_contentobjects_jnotify_linux_JNotify_linux_IN_MOVE_SELF 2048L
#undef net_contentobjects_jnotify_linux_JNotify_linux_IN_UNMOUNT
#define net_contentobjects_jnotify_linux_JNotify_linux_IN_UNMOUNT 8192L
#undef net_contentobjects_jnotify_linux_JNotify_linux_IN_Q_OVERFLOW
#define net_contentobjects_jnotify_linux_JNotify_linux_IN_Q_OVERFLOW 16384L
#undef net_contentobjects_jnotify_linux_JNotify_linux_IN_IGNORED
#define net_contentobjects_jnotify_linux_JNotify_linux_IN_IGNORED 32768L
#undef net_contentobjects_jnotify_linux_JNotify_linux_IN_CLOSE
#define net_contentobjects_jnotify_linux_JNotify_linux_IN_CLOSE 24L
#undef net_contentobjects_jnotify_linux_JNotify_linux_IN_MOVE
#define net_contentobjects_jnotify_linux_JNotify_linux_IN_MOVE 192L
#undef net_contentobjects_jnotify_linux_JNotify_linux_IN_ISDIR
#define net_contentobjects_jnotify_linux_JNotify_linux_IN_ISDIR 1073741824L
#undef net_contentobjects_jnotify_linux_JNotify_linux_IN_ONESHOT
#define net_contentobjects_jnotify_linux_JNotify_linux_IN_ONESHOT -2147483648L
#undef net_contentobjects_jnotify_linux_JNotify_linux_IN_ALL_EVENT
#define net_contentobjects_jnotify_linux_JNotify_linux_IN_ALL_EVENT 2047L
/*
 * Class:     net_contentobjects_jnotify_linux_JNotify_linux
 * Method:    nativeInit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_contentobjects_jnotify_linux_JNotify_1linux_nativeInit
  (JNIEnv *, jclass);

/*
 * Class:     net_contentobjects_jnotify_linux_JNotify_linux
 * Method:    nativeAddWatch
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_net_contentobjects_jnotify_linux_JNotify_1linux_nativeAddWatch
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     net_contentobjects_jnotify_linux_JNotify_linux
 * Method:    nativeRemoveWatch
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_contentobjects_jnotify_linux_JNotify_1linux_nativeRemoveWatch
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_contentobjects_jnotify_linux_JNotify_linux
 * Method:    nativeNotifyLoop
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_contentobjects_jnotify_linux_JNotify_1linux_nativeNotifyLoop
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
