/*******************************************************************************
 * JNotify - Allow java applications to register to File system events.
 * 
 * Copyright (C) 2005 - Content Objects
 * 
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 * 
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
 * 
 ******************************************************************************
 *
 * Content Objects, Inc., hereby disclaims all copyright interest in the
 * library `JNotify' (a Java library for file system events). 
 * 
 * Yahali Sherman, 21 November 2005
 *    Content Objects, VP R&D.
 *    
 ******************************************************************************
 * Author : Omry Yadan
 ******************************************************************************/



 


/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_contentobjects_jnotify_win32_JNotify_win32 */

#ifndef _Included_net_contentobjects_jnotify_win32_JNotify_win32
#define _Included_net_contentobjects_jnotify_win32_JNotify_win32
#ifdef __cplusplus
extern "C" {
#endif
#undef net_contentobjects_jnotify_win32_JNotify_win32_FILE_ACTION_ADDED
#define net_contentobjects_jnotify_win32_JNotify_win32_FILE_ACTION_ADDED 1L
#undef net_contentobjects_jnotify_win32_JNotify_win32_FILE_ACTION_REMOVED
#define net_contentobjects_jnotify_win32_JNotify_win32_FILE_ACTION_REMOVED 2L
#undef net_contentobjects_jnotify_win32_JNotify_win32_FILE_ACTION_MODIFIED
#define net_contentobjects_jnotify_win32_JNotify_win32_FILE_ACTION_MODIFIED 3L
#undef net_contentobjects_jnotify_win32_JNotify_win32_FILE_ACTION_RENAMED_OLD_NAME
#define net_contentobjects_jnotify_win32_JNotify_win32_FILE_ACTION_RENAMED_OLD_NAME 4L
#undef net_contentobjects_jnotify_win32_JNotify_win32_FILE_ACTION_RENAMED_NEW_NAME
#define net_contentobjects_jnotify_win32_JNotify_win32_FILE_ACTION_RENAMED_NEW_NAME 5L
#undef net_contentobjects_jnotify_win32_JNotify_win32_FILE_ACTION_ANY
#define net_contentobjects_jnotify_win32_JNotify_win32_FILE_ACTION_ANY 7L
/*
 * Class:     net_contentobjects_jnotify_win32_JNotify_win32
 * Method:    nativeInit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_contentobjects_jnotify_win32_JNotify_1win32_nativeInit
  (JNIEnv *, jclass);

/*
 * Class:     net_contentobjects_jnotify_win32_JNotify_win32
 * Method:    nativeAddWatch
 * Signature: (Ljava/lang/String;JZ)I
 */
JNIEXPORT jint JNICALL Java_net_contentobjects_jnotify_win32_JNotify_1win32_nativeAddWatch
  (JNIEnv *, jclass, jstring, jlong, jboolean);

/*
 * Class:     net_contentobjects_jnotify_win32_JNotify_win32
 * Method:    getErrorDesc
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_contentobjects_jnotify_win32_JNotify_1win32_getErrorDesc
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_contentobjects_jnotify_win32_JNotify_win32
 * Method:    nativeRemoveWatch
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_contentobjects_jnotify_win32_JNotify_1win32_nativeRemoveWatch
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
